# Generated by Django 4.0.6 on 2023-02-12 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_gal_product_delete_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gal',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
